version: "3.1"

services:
  personas_db:
    image: mysql:8.0
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: personas_db
      MYSQL_ROOT_USER: root
      MYSQL_USER: rootu
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret 